install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - npm --version
  - npm install || npm install

test_script:
  - npm test

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 10

init:
  - git config --global core.autocrlf false

build: off
deploy: off
